### PR TITLE
Add click event functionality (#44)

### PR DESCRIPTION
**Pull request by geeksilva97**
The following features have been added:

- click event specific cell
  This feature allows you to independently capture events in cells, for that use the **setEventsClickCell(events)**. Where **events**  is a object with the attrs: (task, resource, duration, complete, startdate, enddate). All should be functions.

- click event row
  This feature allow you capture events in a row and get the data of task

- double click event row
  This feature is equals to **click event row** but is handler in a **dblclick event**

### CODE REVIEW

**Comment by mariohmol** [comment]
Hi.. can u apply this changes in a PR here? 

https://github.com/mariohmol/jsgantt-improved

ps: i did the AddItemObject there, its missing the events

**Comment by geeksilva97** [comment]
> Hi.. can u apply this changes in a PR here?
> 
> https://github.com/mariohmol/jsgantt-improved
> 
> ps: i did the AddItemObject there, its missing the events

I do not know if you can get data from my fork. If you know how easy it will be.

**Comment by mariohmol** [comment]
Thanks for that!! Check it out https://mariohmol.github.io/jsgantt-improved/docs/demo.html

**Comment by geeksilva97** [comment]
> Thanks for that!! Check it out https://mariohmol.github.io/jsgantt-improved/docs/demo.html

Awesome!

**Pull request closed without merging**
