### PR TITLE
Scrollbar calculation container styles are moved to CSS

### LINKED ISSUE #238: Custom top level styles can mess with headers
**Describe the bug**
Some style like for example `body > * { display: flex; }` can cause incorrect scrollbar size calculation, which leads to incorrect widths for some elements like headers when vertical scrollbar is enabled.
It's related to recent fixed header support.

**To Reproduce**
1. Add style `body > * { display: flex; }`
2. Set `vTotalHeight` to small enough value to enable vertical scroll.

**Expected behavior**
Headers must be visible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 73

**Additional context**

### PR DESCRIPTION
**Pull request by nidu**
Move scrollbar calculation container styles into CSS, so it can be patched if there are any overlapping styles. Also add `display: block` style for this element.

For example in the project i'm working on we have `body > * { display: flex; }`, which i can't control. It breaks scrollbar calculation. When styles are set from JS - there's nothing i can do, but with CSS class i can patch all these overlapping styles.

Fixes #238

### CODE REVIEW

**Comment by mariohmol** [comment]
good catch!

**Comment by nidu** [comment]
Could you please release a new version with this patch if possible?

**Comment by mariohmol** [comment]
Yes.. i'm just making some merge here cause i was refactoring some things..

**Comment by nidu** [comment]
For some reason lines in `jsgantt.js` are not updated (https://unpkg.com/jsgantt-improved@2.4.3/dist/jsgantt.js, search for 3rd `getScrollbarWidth` entry), but `utils.ts` has correct code (https://unpkg.com/jsgantt-improved@2.4.3/src/utils.ts)

**Comment by mariohmol** [comment]
you are right.. fixing here

**Comment by mariohmol** [comment]
check the 2.4.4

**Pull request merged**
