### PR TITLE
Click event functionality on the grid cell added

### PR DESCRIPTION
**Pull request by GeekSilva97**
I recently needed to use the gantt chart in a project and get here. I made an adaptation to my need and it turned out to be just the issue #44 .
Two ways have been added to define the event, which can be in each cell or in the whole row. The **test.html** file has an example usage.

### CODE REVIEW

**Comment by FabianTomoko** [comment]
Returns wrong ID. Am i doing wrong?
``g.setEventClickRow(function(task){
	alert(task.id);
});``

**Comment by codesilva** [comment]
I'll check this bug

**Comment by GeekSilva97** [comment]
I'll check this bug

**Comment by GeekSilva97** [comment]
Solved. See #61

**Pull request closed without merging**
